# -*- coding: utf-8 -*-
{
    "name": "Biometric Device Integration",
    "version": "17.0.1.0.0",
    "category": "Human Resources",
    "summary": "Integrating Biometric Device, Biometric Device, ZKteco, uFace 202, HR Attendance, Odoo Biometric Device, Device Integration, Odoo17, Odoo Apps",
    "author": "Umair Abbas",
    "company": "Rainbow Printing Solutions",
    "maintainer": "Umair Abbas",
    "depends": ["base_setup", "hr_attendance", "hr_contract", "hr", "resource"],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "data/rest_days.xml",
        "views/biometric_device_details_views.xml",
        "views/hr_employee_views.xml",
        "views/daily_attendance_views.xml",
        "views/biometric_device_attendance_menus.xml",
        "data/biometric_cron.xml",
        "views/resource_calendar_views.xml",
        "views/employee_shift_views.xml",
        "views/hr_contract_views.xml",
        "views/hr_attendance_views.xml",
        "views/hr_rest_day_views.xml",
        "views/hr_attendance_search_view.xml",
        "views/biometic_machine_data_views.xml",
        "views/res_users_views.xml",
        "wizard/shift_adjustment.xml",
        "wizard/bulk_shift_change.xml",
    ],
    "license": "AGPL-3",
    "installable": True,
    "auto_install": False,
    "application": False,
}
